#!/bin/sh
### BEGIN INIT INFO
# Provides:          zabbix_proxy
# Required-Start:    $all
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Zabbix proxy
# Description:       Zabbix proxy daemon
### END INIT INFO
#
# Zabbix daemon start/stop script.
#
# Copyright (C) 2001-2016 Zabbix SIA

NAME=zabbix_proxy
DAEMON=/usr/local/sbin/${NAME}
DESC="Zabbix proxy daemon"
PID=/tmp/$NAME.pid

test -f $DAEMON || exit 0

case "$1" in
  start)
	echo "Starting $DESC: $NAME"
	start-stop-daemon --start --oknodo --pidfile $PID --exec $DAEMON
	;;
  stop)
	echo "Stopping $DESC: $NAME"
	start-stop-daemon --stop --quiet --pidfile $PID --retry=TERM/10/KILL/5 && exit 0
	start-stop-daemon --stop --oknodo --exec $DAEMON --name $NAME --retry=TERM/10/KILL/5
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
